/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncState: typeof import('./../components/common/AsyncState.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorBoundary: typeof import('./../components/common/ErrorBoundary.vue')['default']
    Header: typeof import('./../components/layout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/layout/Sidebar.vue')['default']
  }
}

// For TSX support
declare global {
  const AsyncState: (typeof import('./../components/common/AsyncState.vue'))['default']
  const ElButton: (typeof import('element-plus/es'))['ElButton']
  const ElCard: (typeof import('element-plus/es'))['ElCard']
  const ElCol: (typeof import('element-plus/es'))['ElCol']
  const ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
  const ElForm: (typeof import('element-plus/es'))['ElForm']
  const ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
  const ElIcon: (typeof import('element-plus/es'))['ElIcon']
  const ElInput: (typeof import('element-plus/es'))['ElInput']
  const ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
  const ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
  const ElResult: (typeof import('element-plus/es'))['ElResult']
  const ElRow: (typeof import('element-plus/es'))['ElRow']
  const ElSkeleton: (typeof import('element-plus/es'))['ElSkeleton']
  const ElTable: (typeof import('element-plus/es'))['ElTable']
  const ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
  const ElTag: (typeof import('element-plus/es'))['ElTag']
  const ErrorBoundary: (typeof import('./../components/common/ErrorBoundary.vue'))['default']
  const Header: (typeof import('./../components/layout/Header.vue'))['default']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const Sidebar: (typeof import('./../components/layout/Sidebar.vue'))['default']
}
